DELETE http://localhost:8080/concepts/atari

###
POST http://localhost:8080/concepts
Content-Type: application/json

{
  "word": "atari",
  "description": "een onbesliste stand, waarin groepen leven zonder twee ogen"
}

###


GET http://localhost:8080/concepts

